#!/bin/csh
if ( ! $?LT_SRC_HOME ) then
   setenv LT_SRC_HOME "/home/dev/src"
endif
setenv LIRIC_SRC_HOME	        ${LT_SRC_HOME}/liric
setenv LIRIC_NOGIT_SRC_HOME	${LT_SRC_HOME}/liric-nogit
if ( ! $?LT_BIN_HOME ) then
   setenv LT_BIN_HOME "/home/dev/bin"
endif
setenv LIRIC_BIN_HOME	${LT_BIN_HOME}/liric
mkdir -p ${LIRIC_BIN_HOME}
mkdir -p ${LIRIC_BIN_HOME}/scripts
mkdir -p ${LIRIC_BIN_HOME}/detector/c/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/detector/test/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/filter_wheel/c/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/filter_wheel/test/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/fmt
mkdir -p ${LIRIC_BIN_HOME}/usb_pio/c/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/usb_pio/test/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/nudgematic/c/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/nudgematic/test/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/c/${HOSTTYPE}/
mkdir -p ${LIRIC_BIN_HOME}/java
#
# Create fmt soft-links from liric-nogit src directory
#
cd ${LIRIC_BIN_HOME}/fmt
foreach fmtfile ( rap_1000ms.fmt rap_100ms.fmt rap_bias.fmt )
    set file = "${LIRIC_NOGIT_SRC_HOME}/fmt/${fmtfile}"
    if ( ! -e ${fmtfile} ) then
	ln -s ${file}
    endif
end
