#!/bin/csh
if ( ! $?LT_DOC_HOME ) then
   setenv LT_DOC_HOME "/home/dev/public_html"
endif
setenv RAPTOR_DOC_HOME	${LT_DOC_HOME}/raptor
mkdir -p ${RAPTOR_DOC_HOME}
mkdir -p ${RAPTOR_DOC_HOME}/filter_wheel/cdocs/
mkdir -p ${RAPTOR_DOC_HOME}/filter_wheel/test/
