#!/bin/csh
if ( ! $?LT_DOC_HOME ) then
   setenv LT_DOC_HOME "/home/dev/public_html"
endif
setenv LIRIC_DOC_HOME	${LT_DOC_HOME}/liric
mkdir -p ${LIRIC_DOC_HOME}
mkdir -p ${LIRIC_DOC_HOME}/detector/cdocs/
mkdir -p ${LIRIC_DOC_HOME}/detector/test/
mkdir -p ${LIRIC_DOC_HOME}/filter_wheel/cdocs/
mkdir -p ${LIRIC_DOC_HOME}/filter_wheel/test/
mkdir -p ${LIRIC_DOC_HOME}/usb_pio/cdocs/
mkdir -p ${LIRIC_DOC_HOME}/usb_pio/test/
mkdir -p ${LIRIC_DOC_HOME}/nudgematic/cdocs/
mkdir -p ${LIRIC_DOC_HOME}/nudgematic/test/
mkdir -p ${LIRIC_DOC_HOME}/cdocs/
mkdir -p ${LIRIC_DOC_HOME}/deployment/
